### PR TITLE
Adding code to read plugin bootstraps

### PR DESCRIPTION
**Pull request by chrisjohnson1988**
# Introduction

The following pull request adds the ability for plugins to be able to describe the various parts of themselves such that only one file will need to be imported for each plugin. I have left in place the existing wiring, for current plugins, but this could be removed if the approach is adopted.

# How does it work

Essentially, in `src/app/plugins.js` you can add import statements to plugin specific `pulsetile.plugin.js` files. The contents of one of these might look something like this:

```
import routes from "./index.route";
import reducer from "./clinicalstatements-reducer-all";
import clinicalstatementsListComponent from './clinicalstatements-list.component';
import clinicalstatementsCreateComponent from './clinicalstatements-create.component';
import clinicalstatementsDetailComponent from './clinicalstatements-detail.component';
import clinicalstatementsActions from './clinicalstatements-actions';
export default {
  "name": 'clinicalStatements',
  "routes": routes,
  "reducer": reducer,
  "components": {
    clinicalstatementsListComponent,
    clinicalstatementsCreateComponent,
    clinicalstatementsDetailComponent
  },
  "actions": {
	  clinicalstatementsActions
  }
}
```

You can see that this file describes the various aspects of the plugin and links to the parts of the code which map either to angular or redux aspects of the plugin.

Then within  `src/app/plugins.js` you would add a single reference to this file: e.g.

```
import clinicalStatements from './rippleui/pages/clinical-statements/pulsetile.plugin';

export default [
	clinicalStatements
]
```

Having done this, the plugin will be wired up to the application. Any changes to the routing or actions aspect can then be maintained within the plugin repository.

# Reviewing

This is a first go at developing a way to easily add new plugins to the application. It might well be that we can use aspects of angulars **dependency injection** to simplify this further. However I believe this to be beyond the initial exploration of this approach.

Hopefully this provides food for though 😃

### CODE REVIEW

**Comment by vadimivanov** [comment]
Hi, @chrisjohnson1988!
In fact we've done some slight changes to code, and currently we are using the similar approach to the plugin attachment to the core application - we've separated components of a plugin into a single index.js file (that's located within plugin's folder), and, basically what we're doing now - we are 'calling' that plugin from app/index.js file. You can check the 'develop' branch - it's been done for some time already. 

Can you please try to adapt your plugin to this changes, and update pull request? 
Thanks, 
Vadim.

**Comment by tony-shannon** [comment]
thanks Vadim

Sorry to say that Chris had to finish up on the project yesterday.
Can we do those changes ourselves please?

thanks
Tohy

**Comment by vadimivanov** [comment]
Sure, @tony-shannon , I’ll do the necessary changes in the plugin

**Comment by tony-shannon** [comment]
Many thanks Vadim
T

**Comment by PhilBarrett** [comment]
@dkryvosheya could you take a look at this please again and assess if any conflicts before actioning (if required). Thanks

**Comment by tony-shannon** [comment]
@dkryvosheya need an update on what happened here please
thanks
T

**Comment by tony-shannon** [comment]
thanks @dkryvosheya
Assume the related improvements already made it into the codebase
Can you confirm please?
thanks
T

**Comment by dkryvosheya** [comment]
Yes, those changes took place mid-february this year, @tony-shannon

**Pull request closed without merging**
